[2018-10-22 19:00:25,029] INFO [GroupCoordinator 0]: Preparing to rebalance group view with old generation 4 (__consumer_offsets-43) (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:00:25,031] INFO [GroupCoordinator 0]: Stabilized group view generation 5 (__consumer_offsets-43) (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:00:25,032] INFO [GroupCoordinator 0]: Assignment received from leader for group view for generation 5 (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:04:47,784] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-10-22 19:05:25,169] INFO [GroupCoordinator 0]: Preparing to rebalance group view with old generation 5 (__consumer_offsets-43) (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:05:25,170] INFO [GroupCoordinator 0]: Group view with generation 6 is now empty (__consumer_offsets-43) (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:07:26,618] INFO [GroupCoordinator 0]: Preparing to rebalance group view with old generation 6 (__consumer_offsets-43) (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:07:26,619] INFO [GroupCoordinator 0]: Stabilized group view generation 7 (__consumer_offsets-43) (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:07:26,620] INFO [GroupCoordinator 0]: Assignment received from leader for group view for generation 7 (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:08:15,901] INFO [GroupCoordinator 0]: Member kafka-python-1.4.3-d47a3f41-5542-490b-aa2f-4cac11080738 in group view has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:08:15,902] INFO [GroupCoordinator 0]: Preparing to rebalance group view with old generation 7 (__consumer_offsets-43) (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:08:15,902] INFO [GroupCoordinator 0]: Group view with generation 8 is now empty (__consumer_offsets-43) (kafka.coordinator.group.GroupCoordinator)
[2018-10-22 19:14:47,784] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-10-22 19:22:42,199] INFO Unable to read additional data from server sessionid 0x1000051daad0000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:44,052] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:22:44,056] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2018-10-22 19:22:44,057] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2018-10-22 19:22:44,225] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:44,225] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:44,328] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2018-10-22 19:22:46,204] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:46,205] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:47,505] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:47,506] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:48,426] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:22:49,210] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:49,210] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:49,417] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:22:49,794] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:22:50,178] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:22:50,554] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:22:50,907] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:50,908] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:52,305] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:52,306] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:53,870] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:53,870] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:55,902] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:55,903] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:57,785] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:57,786] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:58,932] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:22:58,932] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:00,442] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:00,442] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:01,877] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:01,878] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:03,648] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:03,649] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:04,872] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:04,872] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:06,622] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:06,623] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:07,793] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:23:07,976] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:23:08,173] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:23:08,353] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:23:08,409] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:08,410] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:08,520] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:23:08,680] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2018-10-22 19:23:09,686] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-10-22 19:23:09,687] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
